### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-8: ordinal not in range(256)

### ISSUE THREAD

**Issue by VHEMaster** [porthole-ascend-cinnamon/mhddos_proxy_releases#10]
Ubultu 20.04 LTS, after cloning and starting getting this message

```
root@web311:~# ./mhddos_proxy_linux
Traceback (most recent call last):
  File "<dist/obf/runner.py>", line 2, in <module>
  File "<frozen runner>", line 624, in <module>
  File "<frozen runner>", line 514, in main
  File "<frozen src.output>", line 68, in print_banner
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-8: ordinal not in range(256)
[268702] Failed to execute script 'runner' due to unhandled exception!
root@web311:~#

```

**Comment by porthole-ascend-cinnamon** [comment]
I am not exactly sure why this happens, but switching to English lang should help  `./mhddos_proxy_linux --lang en`

**Comment by VHEMaster** [comment]
It doesn't help. Error is the same

пн, 8 авг. 2022 г., 19:18 porthole-ascend-cinnamon ***@***.***

**Comment by porthole-ascend-cinnamon** [comment]
Hmm. Something is wrong with your server locales, so stdout is not utf8 but latin-1. Try reconfiguring them (something from here may work https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue), unfortunately I cannot provide more specific instructions, only way to know is to try stuff.  Alternatively you can send me credentails to porthole-ascend-cinnamon@protonmail.com and I'll try to fix when I have time
