### ISSUE TITLE
Please, add RX rate limit option

### ISSUE THREAD

**Issue by alokym86** [porthole-ascend-cinnamon/mhddos_proxy_releases#12]
This app uses almost all my outgoing bandwidth. I'd tried to downgrade performance with `-t` arg as a workaround but it is unpredictable for traffic usage. So, please, let my son learn by Zoom and my raspberry to ddos rusnyu simultaneously.

**Comment by porthole-ascend-cinnamon** [comment]
Hi! We would love to, but it's very tricky. There are no viable solutions as for now, unfortunately. The best shot would be to somehow limit from the outside, on OS/network level. Quick search lead me to this one - maybe you could give at a try and tell us how it went. https://github.com/magnific0/wondershaper

**Comment by alokym86** [comment]
Hi! I had already tried wondershaper from Ubuntu 20.04 repositories. And it did not reduce mhddos_proxy outgoing traffic. But the [latest version](https://github.com/magnific0/wondershaper) (currently 1.4.1) works like a charm!

**Comment by porthole-ascend-cinnamon** [comment]
Huh, weird. But it works and that's good
