### ISSUE TITLE
mhddos_proxy fails on raspberry pi 3

### ISSUE THREAD

**Issue by Leksyk** [porthole-ascend-cinnamon/mhddos_proxy_releases#19]
Fails with:
 -bash: .[/mhddos_proxy_linux_arm64](tg://bot_command?command=mhddos_proxy_linux_arm64): cannot execute binary file: Exec format error"

Can it be compiled for any of the raspberry pi versions as well?

**Comment by porthole-ascend-cinnamon** [comment]
I am afraid no other binaries can/will be provided in the foreseeable future

**Comment by alokym86** [comment]
@Leksyk, `mhddos_proxy_linux_arm64` works on Raspberry Pi (Raspberry Pi 4 with Ubuntu 20.04 in my case). Does your system support `arm86` arch? Please, look at #13

**Comment by Leksyk** [comment]
@alokym86 I got Raspberry PI 4 but it still doesn't work (same error as for RP 3).

> cat /proc/version

```
Linux version 5.15.76-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1597 SMP Fri Nov 4 12:14:58 GMT 2022
```

Any suggestions?

**Comment by alokym86** [comment]
`mhddos_proxy_linux_arm64` requires `arm64` libraries. In case it doesn't matter which OS is installed on your Raspberry PI 4 (or 3), install `arm64` version of [Ubuntu](https://ubuntu.com/download/raspberry-pi) - it is the easiest way in my opinion. Or you can try to install missed libs with
```
# dpkg --add-architecture arm64
# apt-get update
# apt-get install libc6:arm64
```
