### ISSUE TITLE
ARM version missing?

### ISSUE THREAD

**Issue by C0ntr07** [porthole-ascend-cinnamon/mhddos_proxy_releases#2]
Getting this error message. 

Here is the command I'm running. 

`docker run -it --rm --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy -t 8000 --vpn --lang EN
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:6bbf0e10b4a6dc729531d1b39eade7aeaef74c3420fabfbd14b6d4b6d2c4a35f
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error`

This is what I am running. 

`uname -a 
Linux ethereum 5.15.41-v8+ #1557 SMP PREEMPT Mon May 23 16:53:08 BST 2022 aarch64 GNU/Linux`

**Comment by porthole-ascend-cinnamon** [comment]
Hi, we never supported arm/v7, did it work for you on the previous versions?

**Comment by baragoon** [comment]
previous versions runs fine via python, now we can't use this great soft on raspberry pi or similar hw

**Comment by porthole-ascend-cinnamon** [comment]
@baragoon the issue is about docker support for arm/v7, please open another one for other platforms and provide all the details. It's not straightforward to support everything, and given small userbase it's just not worth the time it would take, but would see

**Comment by rnd49** [comment]
arm64/v8 container also missing
```
docker run -it --rm -d --pull always ghcr.io/porthole-ascend-cinnamon/mhddos_proxy --itarmy
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
Digest: sha256:6bbf0e10b4a6dc729531d1b39eade7aeaef74c3420fabfbd14b6d4b6d2c4a35f
Status: Image is up to date for ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ea7c2bbaad76ec250e563da923a1e31c6986e30d5470d439b4d6e1a27fa15ad0
```


Is it planned to provide arm64 binaries or container?

**Comment by porthole-ascend-cinnamon** [comment]
@rnd49 same, open a new issue, do not [hijack the thread](https://www.urbandictionary.com/define.php?term=Thread%20Hijacking). 
It should work fine on arm64, at least on a M1 mac which were tested

**Comment by C0ntr07** [comment]
That's what's confusing too. I'm running V8 but get a V7 message.

`uname -a Linux ethereum 5.15.41-v8+ #1557 SMP PREEMPT Mon May 23 16:53:08 BST 2022 aarch64 GNU/Linux`

**Comment by porthole-ascend-cinnamon** [comment]
Added in v52, both binary and docker
