### ISSUE TITLE
Автозапуск

### ISSUE THREAD

**Issue by AlexNemets** [porthole-ascend-cinnamon/mhddos_proxy_releases#20]
Підскажіть будь ласка таке питання: чи можливо зробити так, щоб при запуску, коли немає інтернет з`єднання, mhddos не припиняв роботу, а намагався з`еднатися? Робиться 4 спроби з`єднання і программа завершує роботу :-( в мене за цей час роутер не встигае під`єднатися до провайдера.... Дякую. Смерть ворогам!

**Comment by porthole-ascend-cinnamon** [comment]
Добрий день, взяли в роботу

**Comment by porthole-ascend-cinnamon** [comment]
Остання версія буде перезапускатися автоматично допоки зв'язок не відновиться
