### ISSUE TITLE
Використання мікрокомп‘ютеру Raspberry Pi

### ISSUE THREAD

**Issue by SergeiKDW** [porthole-ascend-cinnamon/mhddos_proxy_releases#23]
Мене цікавило питання чи можна використати мікрокомп‘ютери Raspberry Pi під mhddos_proxy, чи вистачить потужності, чи не буде перегріву та тротлінгу тощо. Не знайшов такої інформації на сайті IT ARMY, тут також не було нічого, та відповісти щось конкретне ніхто не зміг. Інформації дуже мало.

Я дослідив це питання особисто. Результат позитивний. Ділюся результатами та думками. Можливо, бажаючим допомогти Україні буде корисно для практичного використання та як наслідок більше людей зможуть доєднатися. Бо рішення на базі Raspberry Pi виходить дуже зручним у використанні.

**ПЕРЕВАГИ:**
1. Займає мало місця. Розмір приблизно як пачка з під сигарет.
2. Повністю безшумний. Немає дискомфорту для оточуючих. Можна розміщувати хоч поруч з ліжком.
3. Можна налаштувати автозапуск mhddos_proxy після увімкнення живлення. Доволі стабільно працює. А враховуючи автооновлення mhddos_proxy та автооновлення цілей отримуємо автономну систему, що сама запускається при відновленні живлення, не потребує ручної роботи по запуску, значного контролю тощо. Тож можна один раз налаштувати та "забути".
4. Споживає значно менше енергії порівняно з повноціннними компьютерами: 2-4 Вт, в середньому 3 Вт (при параметрі thread=700-1000). Витрати енергії низькі. Це гарно і для країни і для корстувача.
5. Може живитися від зарядного пристрою для смартфону через USB-кабель (бажано чесний зарядний пристрій на 2А та більше). Також можна живити від UPS для роутеру з USB виходом. Або павербанку. Це велика перевага при відключеннях світла, якщо у вас є автономний канал інтернет, UPS буде підтримувати роботу Raspberry Pi з mhddos_proxy.
6. Можливість кабельного Ethetnet-підключення до роутера. Це робить роботу більш стабільною та не навантажує wi-fi мережу. Хоча wi-fi підключення (також є).
7. Можна налагодити цілодобову роботу 24х7.
8. Linux-подібна безкоштовна операційна система Raspberry Pi OS від виробника з регулярними оновленнями. Заснована на Debian, схожа Ubuntu та інші засновані на Debian. Тим хто вже вміє працювати в таких системах, буде легко працювати і в цій.
9. Можна встановити Ubuntu.  
10. Теоритично можна гнучко налаштувати режими роботи, якщо, наприклад, хочете вночі збільшити кількість threads тощо.
11. Також можна на тому самому мінікомп‘ютері запускати й інші сервіси, наприклад, щось для розумного дому тощо.
12. Великий вибір аксесуарів. Наприклад, можна підібрати корпус з кріпленням на стіну тощо.

**НЕДОЛІКІ:**
1. Як для маленької плати, психологічно, недешева ціна на самі останні, потужні моделі з великим об‘ємом оперативної пам‘яті  ;-)

Але схоже для mhddos_proxy вистачить і старих моделей. Наприклад, Raspberry Pi model B з 1GB в США коштує приблизно $42.

Виходить доволі гарний маленький та стабільний комп‘ютер, якій можна підключити до роутера та не витрачати багато часу на обслуговування. Він буде працювати сам по собі. При зникненні електрики (без UPS) та відновленні сам запустится за пару хвилин та автоматично почне роботу mhddos_proxy. Вам не треба бути поруч, запускати вручну тощо, приділяти багато уваги цьому тощо. Займає мало місця, не шумить не затягує в себе пил як звичайні комп‘ютери. Тож, час та витрати на обсуговування і підтримання будуть мінімальні, а  час роботи mhddos_proxy максимальним.

Ціна комплекту обладнання буде на рівні з дешевими комп‘ютерами, що були у викорситанні. Але у комп‘ютерів споживання зазвичай 20-40 Вт та вище в деяких випадках, шум, пил всередені який треба час від часу чистити, знос вентиляторів, займають більше місця тощо.

При правильному налаштуванні та підключені можна розмістити у "нетехнічних" друзів, які хочуть приєднатися, але не хочуть вивчати як це все запускати тощо. У них є бажання просто встановити, хай працює, перезавантажити час від часу. Але не заглиблюватись в налаштування.

Повинно стабільно працювати, запускатися після відключень електрики тошо. Контролювати можна по блиманню индикатора на ethernet-роз‘ємі. У випадку необхідності перезавантажити, достатньо просто витягти з розетки та увімкнути знову. Для нетехнічних юзерів це просто та зрозуміло.

**ЩО ВИКОРИСТОВУВАВ:**
Викорстовував мікрокомп‘ютер Raspberry Pi model B з 1GB оперативної пам‘яті.
 
В основному, параметр threads на значенні 700-1000. Бо при великих значеннях та певних списках цілей було що провайдер робив зауваження. Тож краще працювати меншим потоком стабільно цілодобово, чим взагалі вимкнути.
Навантаження на процесор приблизно 15% в середньому. Може змінюватися від 2 до 45% короткочасно. споживання енергії приблизно 3 Вт в середньому.
Нагріву не помітив. Тротлінгу також.

Якщо потрібно покращити відведення тепла від процесора, можна легко встановити (самоклейка) на процесор маленький радіатор (пасивний, без вентилятора). Ціна приблизно $0.5-1.

Короткочасно ставив параметр threads в 2000 та більше. Не помітив якихось проблем в роботі. Я не ставлю великі значення, щоб не було зауважень від провайдера.

**ПРОПОЗИЦІЇ:**
Пропоную розробникам додати в інструкції (в тому числі на сайті IT ARMY) інформацію про те, що mhddos_proxy нормально працює на мікрокомп‘ютерах Raspberry Pi та за можлисті короткій мануал з кроками, як встановити Raspberry Pi OS або Ubuntu, зробити автозапуск mhddos_proxy як служби, тощо. Таким чином більше людей зможуть приєднатися до участі в міссії IT ARMY.

**Comment by porthole-ascend-cinnamon** [comment]
Добрий день! Надішліть будь ласка на пошту porthole-ascend-cinnamon@protonmail.com свій телеграм, з вами зв'яжуться.

**Comment by AndrejGorodnij** [comment]
Дуже корисна інформація, дякую. Це питання також цікавило, хоча власної малинки не маю, але гадаю є сенс зробити ресьорч на ОЛХ, можливо зроблю невеликий кластер для цілодобової роботи...
