### ISSUE TITLE
Doesn't work inside a WHONIX Debian terminal?

### ISSUE THREAD

**Issue by Oswobodilnik** [porthole-ascend-cinnamon/mhddos_proxy_releases#24]
Hello the program doesn't start inside this terminal and it doesn't update?

What should I do?

All information - https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases

[14:03:34 - WARNING] Could not perform an update
[14:03:35 - INFO] Launching the attack...
[14:03:35 - ERROR] Failed to load system config

Restarting in 30s...

**Comment by porthole-ascend-cinnamon** [comment]
Please refer to the https://t.me/+H6PnjkydZX0xNDky for technical support support
