### ISSUE TITLE
Hangs after some time and the laptop becomes unresponsive

### ISSUE THREAD

**Issue by kostenko** [porthole-ascend-cinnamon/mhddos_proxy_releases#26]
M1 Mac, running from docker, giving it 6 CPUs out of 10, 32GB RAM out of 64, 2GB swap. If I don't kill and restart the command after an hour or two — it hangs everything.

**Comment by kostenko** [comment]
I can't even sudo kill docker processes — all hangs and only hard reboot works

**Comment by porthole-ascend-cinnamon** [comment]
Hi! Seems more like a system problem, haven't heard about such problems before.
Pretty weird, given you've limited the docker resources. 
M1 is definitely not 100% great with docker - there were still some unfixed issues last time I checked.
Not much I can recommend -  try lowering mhddos parameters (like 8k threads and 1 or 2 copies) , maybe don't use limits - it won't be able to consume a lot of resources on this settings. 
Another option - run Ubuntu VM ([see this guide](https://gist.github.com/prikid/0cd17e45800f3d4faea6a2be58e8979f))

**Comment by kostenko** [comment]
kk, will close this
