### ISSUE TITLE
32-bit build only for windows?

### ISSUE THREAD

**Issue by sq2mo** [porthole-ascend-cinnamon/mhddos_proxy_releases#27]
Why is windows OS privileged to have a 32-bit build, but other systems get only 64-bit?

**Comment by porthole-ascend-cinnamon** [comment]
Technical limitations. What platform are you looking for, is it [in this list ](https://github.com/docker-library/official-images#architectures-other-than-amd64)?
 We'll try to take another look, but can't promise anything.

**Comment by porthole-ascend-cinnamon** [comment]
Frankly, 32-bit is quite outdated and have very few users, I would get rid of windows as soon as any problem arises with building it.

**Comment by sq2mo** [comment]
Cool, thanks!
