### ISSUE TITLE
Speed limiting option

### ISSUE THREAD

**Issue by volatileman** [porthole-ascend-cinnamon/mhddos_proxy_releases#29]
Could you add an optional configuration property to set the maximum traffic speed generated by this app?
Or do you know a workaround to make Linux limit the speed?
I tried `tc`, `trickle`, and `wondershaper` but none of them seem to work.

**Comment by alokym86** [comment]
look at #12. `wondershaper` v1.4.1 works perfectly on my raspberry pi with ubuntu 20.04. Version from repositories doesn't work, so try to use latest version from github.

**Comment by volatileman** [comment]
Thanks for the answer. I'm testing `wondershaper` from the GitHub right now. 
It has some effect but it's hard to tell exact numbers. I use `slurm` to monitor the network and it shows some average network usage. So I set the limit of 160Mbitsps and it shows me approximately 4MBps - 6MBps of the outcome traffic.

**Comment by alokym86** [comment]
Here is part of  my crontab
```#---- ddos русні
@reboot         root    sleep 30 && /home/ubuntu/wondershaper/wondershaper -a eth0 -u 8192
@reboot         ubuntu  cd /home/ubuntu/mhddos_proxy/ && screen -dmS "mhddos_proxy" ./mhddos_proxy_linux_arm64 -t 5000
#---------------
```
here I run wondershaper from the downloaded dir as root (but add 30 second delay after boot).

and the output of mhddos_proxy
```
[17:20:18 - INFO] Потоків: 5000 | Атака через проксі та ваш IP/VPN

[17:20:23 - INFO] Потужність: 100.0%, З'єднань: 131, Пакети: 2.04k/s, Трафік: 7.80 MBit/s
[17:20:28 - INFO] Потужність: 100.0%, З'єднань: 137, Пакети: 2.07k/s, Трафік: 7.80 MBit/s
```
and without usage `wondershaper` 
```
[17:24:16 - INFO] Потужність: 100.0%, З'єднань: 158, Пакети: 2.53k/s, Трафік: 13.22 MBit/s
[17:24:21 - INFO] Потужність: 100.0%, З'єднань: 172, Пакети: 2.49k/s, Трафік: 12.48 MBit/s
```

So, please check your path, interface name, and so on, and try again.

**Comment by volatileman** [comment]
Thanks for the answers.
`wondershaper` from GitHub seem to solve the problem
