### ISSUE TITLE
Microsoft забороняє завантажити із GitHub на termux 

### ISSUE THREAD

**Issue by uzvarUA** [porthole-ascend-cinnamon/mhddos_proxy_releases#34]
curl https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases/releases/latest/download/mhddos_proxy_linux -Lo mhddos_proxy_linux 
Error 404

**Comment by porthole-ascend-cinnamon** [comment]
Termux не підтримується. Окрім того, що ви очікуєте від нас, скаргу в майкрософт? )
