### ISSUE TITLE
linux arm v7 version?

### ISSUE THREAD

**Issue by C0ntr07** [porthole-ascend-cinnamon/mhddos_proxy_releases#36]
I have a 42 old 32 bit ARM devices I would like to put to "good use."  I used to be able to run MHDDOS but now there doesn't appear to be a compatible version.  Is there a solution to this?

I also just tried using docker but that doesn't work either.

 `i@RPi-Node41-2B:~ $ sudo docker run -it --rm --pull always --net=host ghcr.io/porthole-ascend-cinnamon/mhddos_proxy
latest: Pulling from porthole-ascend-cinnamon/mhddos_proxy
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.

pi@RPi-Node41-2B:~ $ 
`

**Comment by porthole-ascend-cinnamon** [comment]
Hi. Only ARM 64x is supported and no new platforms planned in the foreseeable future.
I recommend checking out another official instrument - [distress](https://github.com/Yneth/distress-releases/) which should support your devices (either armv7-unknown-linux-musleabi or arm-unknown-linux-musleabi).
